# TODO: AvailabilityZone vs Regions
# TODO: VPCs vs Subnets

Description:
  Deploy ec2 stack with auto-scaling group

Parameters:
  KeyName:
    Type: String
    Default: awscourse
  SSHSubnetId:
    Type: String
    Default: subnet-30432511
  SSHVpcId:
    Type: String
    Default: vpc-3451e549
  ASGSubnets: # list of subnets in VPC TODO: why?
    Type: CommaDelimitedList
    Default: subnet-30432511, subnet-9c4e65d1, subnet-3eeab830, subnet-103f5b4f, subnet-163ea670, subnet-8b8e21ba
  EC2AmiId:
    Type: String
    Default: ami-0e70db31f7e942241
  EC2Type:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  AutoScalingGroupMin:
    Type: Number
    Default: 2
  AutoScalingGroupMax:
    Type: Number
    Default: 4

Resources:
  EC2Launch:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref EC2AmiId
        InstanceType: !Ref EC2Type
        # sudo yum install java-1.8.0-openjdk
        UserData: c3VkbyB5dW0gaW5zdGFsbCBqYXZhLTEuOC4wLW9wZW5qZGs=
        NetworkInterfaces:
          - Groups:
              - Ref: SSHSecurityGroup
            DeviceIndex: 0
        KeyName: !Ref KeyName

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: !Ref AutoScalingGroupMin
      MaxSize: !Ref AutoScalingGroupMax
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2Launch
        Version: !GetAtt EC2Launch.LatestVersionNumber
      VPCZoneIdentifier: !Ref ASGSubnets

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: SSHVpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
